// app.js

require('dotenv').config();

// ... existing code ...

const apiUrl = process.env.API_URL;
const apiKey = process.env.API_KEY;

// Use apiUrl and apiKey in your API requests

// Example of making an API request
const fetch = require('node-fetch');

async function fetchData() {
  const response = await fetch(`${apiUrl}/data`, {
    headers: {
      'Authorization': `Bearer ${apiKey}`
    }
  });
  const data = await response.json();
  console.log(data);
}

fetchData();

// ... existing code ...
API_URL=https://your-api-endpoint.com
API_KEY=your-api-key
name: NodeJS with Gulp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        gulp
